add nooptracer
outrank/spotify_opentelemetry_wrapper_lib pull request #1
Opened 2022-07-08 19:57 UTC by KushalD1999

2022-07-08 20:19 UTC, aabramov-pc requested changes
We shouldn't return anything from this function.

2022-07-08 20:19 UTC, aabramov-pc commented on spotify_opentelemetry_wrapper.py
> +    _disable_logging = os.getenv("OTEL_DISABLE_LOGGING", False)
This should be `disable_logging` - the underscore prefix is typically used to denote private class members

2022-07-08 20:19 UTC, aabramov-pc commented on spotify_opentelemetry_wrapper.py
> +from opentelemetry.trace import NoOpTracerProvider, NoOpTracer
This shouldn't be needed

2022-07-08 20:19 UTC, aabramov-pc commented on spotify_opentelemetry_wrapper.py
> +        return NoOpTracer()
This function doesn't return anything, you can just have `return` here to end execution. When callers try to use the `tracer` object, they will get the default-initialized NoOp tracer (see initialization above).

2022-07-09 19:33 UTC, KushalD1999 commented on spotify_opentelemetry_wrapper.py
> +        return NoOpTracer()
got it, thanks

2022-07-11 12:57 UTC, aabramov-pc approved these changes

2022-07-11 19:05 UTC, merged